In [238]:
from uta_infer import uta_rank
import numpy as np

import numpy as np
np.random.seed(42)
# 200 alternatives avec des floats entre 0 et 500 sur 4 critères
X = np.random.rand(20, 4)
print(X[0:5])

[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]
 [0.30424224 0.52475643 0.43194502 0.29122914]]


In [239]:
order = np.arange(X.shape[0])
np.random.shuffle(order)

res = uta_rank(
    X=X,
    L=5,                     # 5 segments pour *chaque* critère
    order=order,          # ordre donné
    scale="minmax",          # standardisation → [0,100]
    pairs="consecutive",     # contraintes sur pairs successifs
    return_details=True      # pour voir les poids, fonctions, etc.
)

print("Ranking inféré (best→worst):\n", res["ranking"])
print("Poids inférés:", np.round(res["weights"], 4))

Ranking inféré (best→worst):
 [13  2  8  0 15 12  3 10 18  9  5 11  4 17 19  7  6  1 16 14]
Poids inférés: [0.1415 0.0076 0.3432 0.5076]


In [240]:
print("Slack :", res["obj_slack"])

Slack : 1.1955473838973523
